### ISSUE TITLE
onActivityResult not being called

### ISSUE THREAD

**Issue by unTanana** [luisfuertes/react-native-file-picker#17]
Hello, I tried using this package to select a file, in order to upload it. I noticed that nothing is printed in the console after a file is chosen.
The filepicker closes after I choose a file, but no file info is shown. I have even added some logs inside the android code inside both onActivityResult functions to check if they are called.
No logs are shown from those 2 functions, so I assume they are not being called. What can I do to fix this ? thank you!

**Comment by kkrishnan90** [comment]
Is there any solution you've found ? I almost tried all the libraries and it still behaves the same. I don't get the response.

**Comment by unTanana** [comment]
yes, it had to do with expo if I remember correctly. It doesn't work with it. I removed expo from my project, and now it's working.

**Comment by kkrishnan90** [comment]
Ahhhh ! Ok ! Thanks man ! Appreciate your prompt response !

**Comment by unTanana** [comment]
Glad to help :D
