### ISSUE TITLE
UI don't show

### ISSUE THREAD

**Issue by siloebb** [luisfuertes/react-native-file-picker#18]
I'm using the example, I put the permissions and I make the link.

Now when I call the function nothing is shown, in the code it goes straight to setState.

When I print the response is:
'Response = ', { option: 'launchFileChooser', didRequestPermission: true }.

The code:
> FilePickerManager.showFilePicker(options,(response) => {
>       console.log('Response = ', response);
>      
>       if (response.didCancel) {
>         console.log('User cancelled file picker');
>       }
>       else if (response.error) {
>         console.log('FilePickerManager Error: ', response.error);
>       }
>       else {
>         console.log('Escolheu arquivo', response)
>         this.setState({
>           file: response
>         });
>       }
>     });

**Comment by mjmasn** [comment]
I'm also seeing this issue

**Comment by FinCendikia** [comment]
Any updates on this problem?

**Comment by mjmasn** [comment]
@FinCendikia nope but [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) works well for picking/cropping images, and [react-native-document-picker](https://github.com/Elyx0/react-native-document-picker) for picking files (though I highly recommend using the currently unreleased [#v3 branch](https://github.com/Elyx0/react-native-document-picker/tree/v3) - i.e. `yarn add git://github.com/Elyx0/react-native-document-picker#v3`).

**Comment by AtulKondekar** [comment]
@FinCendikia @mjmasn @siloebb Apparently, we also need to add camera permission in android/src/main/AndroidManifest.xml 
`<uses-permission android:name="android.permission.CAMERA" />`

**Comment by luisfuertes** [comment]
Can i close this issue?

**Comment by mjmasn** [comment]
@luisfuertes we're not using this lib anymore, but why is the camera permission needed for picking files? :thinking: Seems like that should be optional (if that is indeed the solution to this issue).

**Comment by luisfuertes** [comment]
This component is based in react-native-image-picker. Maybe some inheritance of it

**Comment by pmiddend** [comment]
@luisfuertes Yes, that might be it. Could you please fix this? Users are wary of permissions these days. Requesting camera access seems fishy (and is unnecessary).
