### ISSUE TITLE
Throw an error if the user is not properly logged in to google.

### ISSUE THREAD

**Issue by DaniAkash** [luisfuertes/react-native-file-picker#2]
If the user is not properly logged in to google (say he has changed his password in a different device), when the file from that account is selected it returns the file data with content property alone.
`{
"content":“content://com.google.android.apps.docs.storage/document/acc%3D10%3Bdoc%3D1227"}`

The uri is missing in the result. It would be easier if it throws an error.

**Comment by luisfuertes** [comment]
Thanks for report.

As soon as I can, i will implement it

**Comment by luisfuertes** [comment]
Can try version v0.0.12?

**Comment by DaniAkash** [comment]
@luisfuertes will test this soon

**Comment by DaniAkash** [comment]
Looks good. Thanks for the fix
