### ISSUE TITLE
undefined is not an object (evaluating 'FilePickerManager.showFilePicker')

### ISSUE THREAD

**Issue by mghifariyusuf** [luisfuertes/react-native-file-picker#22]
I have followed every step correctly, but there's an error like this:

> undefined is not an object (evaluating 'FilePickerManager.showFilePicker')

How to solve this error? Thanks ^^

**Comment by koswarabilly** [comment]
have you import it?

**Comment by mghifariyusuf** [comment]
@koswarabilly sorry I forgot about this, because it's been a long time I asked it
