### ISSUE TITLE
Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by pgonzalez-santiago** [luisfuertes/react-native-file-picker#23]
Hey everyone,

everytime I try to make a `npm install` I get this error message:

`/Users/pgon1i/Documents/Projects/linde-app/node_modules/react-native-file-picker: Appears to be a git repo or submodule.`

How can I solve it?

RN version: 0.48.3
react-native-file-picker version: 0.0.11

Thank you.

**Comment by lube** [comment]
https://github.com/APSL/react-native-version-number/issues/13#issuecomment-341059894

> +1 I am also having this issue. As @alexgvozden mentions, the package needs to be updated to remove the .git directory from the package. As a temporary fix for @sdduursma , just go into the directory and use rm -rf .git this will stop NPM complaining.

**Comment by luisfuertes** [comment]
`.npmignore` added on v0.0.12

**Comment by Henry-C-Lo** [comment]
> `.npmignore` added on v0.0.12

Can we get a little more info on this solution?

**Comment by codebased** [comment]
I had a similar issue with react-native-gesture-handler. 

> verb stack Error: C:\Projects\xx\node_modules\react-native-safe-area-view: Appears to be a git repo or submodule.
> npm verb stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:137:15
> npm verb stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:285:20
> npm verb stack     at FSReqCallback.oncomplete (fs.js:149:5)
> npm verb cwd C:\Projects\CitizenshipMate
> npm verb Windows_NT 10.0.17763
> npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-native-gesture-handler" "--verbose"
> npm verb node v12.2.0
> npm verb npm  v6.9.0
> npm ERR! path C:\Projects\xx\node_modules\react-native-safe-area-view
> npm ERR! code EISGIT
> npm ERR! git C:\Projects\xx\node_modules\react-native-safe-area-view: Appears to be a git repo or submodule.
> npm ERR! git     C:\Projects\xx\node_modules\react-native-safe-area-view
> npm ERR! git Refusing to remove it. Update manually,
> npm ERR! git or move it out of the way first.
> 
> 

Solution: I went into  C:\Projects\xx\node_modules\react-native-safe-area-view and deleted .git folder. Then I was able to run npm install successfully.

**Comment by YukihiroYamashita** [comment]
@codebased this solution worked for me, thx

**Comment by saeedhemmati** [comment]
> I had a similar issue with react-native-gesture-handler.
> 
> > verb stack Error: C:\Projects\xx\node_modules\react-native-safe-area-view: Appears to be a git repo or submodule.
> > npm verb stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:137:15
> > npm verb stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:285:20
> > npm verb stack     at FSReqCallback.oncomplete (fs.js:149:5)
> > npm verb cwd C:\Projects\CitizenshipMate
> > npm verb Windows_NT 10.0.17763
> > npm verb argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "--save" "react-native-gesture-handler" "--verbose"
> > npm verb node v12.2.0
> > npm verb npm  v6.9.0
> > npm ERR! path C:\Projects\xx\node_modules\react-native-safe-area-view
> > npm ERR! code EISGIT
> > npm ERR! git C:\Projects\xx\node_modules\react-native-safe-area-view: Appears to be a git repo or submodule.
> > npm ERR! git     C:\Projects\xx\node_modules\react-native-safe-area-view
> > npm ERR! git Refusing to remove it. Update manually,
> > npm ERR! git or move it out of the way first.
> 
> Solution: I went into C:\Projects\xx\node_modules\react-native-safe-area-view and deleted .git folder. Then I was able to run npm install successfully.

Thanks, it's worked for me

**Comment by codebased** [comment]
Thanks guys! Do give me a upvote in stack over flow :)
