### ISSUE TITLE
react-native link unsuccessful

### ISSUE THREAD

**Issue by CocktailZY** [luisfuertes/react-native-file-picker#24]
Cannot load module file 'F:/svn_project/InstantMessage/node_modules/react-native-file-picker/android/react-native-file-picker.iml':
File F:\svn_project\InstantMessage\node_modules\react-native-file-picker\android\react-native-file-picker.iml does not exist
Would you like to remove module 'react-native-file-picker' from the project?

I check the directory , only have react-native-image-picker.iml

**Comment by luisfuertes** [comment]
If i rename `react-native-image-picker.iml` to `react-native-file-picker.iml` it will work?
