### ISSUE TITLE
Getting IllegalArgumentException: Unknown URI when running on Android 8

### ISSUE THREAD

**Issue by jiankai82** [luisfuertes/react-native-file-picker#26]
I am getting the following exception when running the this file picker plugin on a device with Android 8 (Oreo):

java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/1234

It works fine on Android 7.

Any ideas?

The exception occurs at the following line in FilePickerModule.java

cursor = context.getContentResolver().query(uri, projection, selection, selectionArgs, null);

**Comment by japetheape** [comment]
Samsung S9 running Android 8.0 throws this error for us, other devices don't.

**Comment by jiankai82** [comment]
Any idea how to fix it?

**Comment by arunarajput** [comment]
Anyone have any idea about the same? I have the same issue.

**Comment by marotan3** [comment]
I juist created  PR #29 that fixes it for us

**Comment by luisfuertes** [comment]
Thanks @marotan3. PR pubished on v0.0.12
