### ISSUE TITLE
How can i pick file by its type??

### ISSUE THREAD

**Issue by tjsaini007** [luisfuertes/react-native-file-picker#4]
Hello Sir, 
Thanks for your library but i have a issue, How can i pick file by its type, like i want to pick only Images, DOC, or PDF etc. 
will you help me to solve this issue??

**Comment by luisfuertes** [comment]
Actually, when i receive the url do:

``` 
    let fileExtension = Commons.Utils.getFileExtension(url)
    if(fileExtension && fileExtension.isValid){

    }else{
        Alert.alert('Error', 'File extension error')
    }


export function getFileExtension(url){
  try {
    let extension = url.split('.').pop()
    const extensionList = Constants.validExtensionList
    let isValid = extensionList.indexOf(extension) == -1 ? false : true
    return {extension: extension, isValid: isValid}
  }catch(error) {
    console.warn("getFileExtension error: ", error)
    return {extension : '', isValid: false}
  }
}
```

It can help you for now. But i will try to implement this in the module.

Regards

**Comment by rajeshkos** [comment]
Is this also work for IOS ?

**Comment by luisfuertes** [comment]
This component does not work on iOS.

On iOS you can [use this component](https://github.com/Elyx0/react-native-document-picker)

**Comment by ansal-exp** [comment]
@luisfuertes any update on this?
