### ISSUE TITLE
how can i store the file on server?

### ISSUE THREAD

**Issue by ShanthiSenguttuvan** [luisfuertes/react-native-file-picker#5]
I am using your module. its working good. But i don't know how to save the picked file in my node js server. I am getting path and url only. Is there any option to get base 64 encoded data of the picked file?

**Comment by abdurrahmanekr** [comment]
@ShanthiSenguttuvan use [RNFetchBlob](https://github.com/wkh237/react-native-fetch-blob)
```javascript
var data = '';
RNFetchBlob.fs.readStream(
	res.uri,
	'base64',
	12285)
.then((ifstream) => {
	ifstream.open();
	ifstream.onData((chunk) => {
		data += chunk
	});
	ifstream.onError((err) => {
		console.log('error', err);
	})
	ifstream.onEnd(() => {
		console.log('is finished!');
		console.log(data)
	})
})
```
see #8

**Comment by luisfuertes** [comment]
Thanks for answer @abdurrahmanekr 

I close this issue
